# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
     curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
     chmod +x ./snyk
     mv ./snyk /usr/local/bin/
     sudo apt-get update && sudo apt-get install snyk-to-html -y
     mkdir -p snyk-result
     snyk auth $(SYNC_TOKEN)
     snyk test --all-projects
  env:
    SYNC_TOKEN: $(SYNC_TOKEN)
  displayName: 'Security Scan'
