# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
     curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
     chmod +x ./snyk
     mv ./snyk /usr/local/bin/
     sudo apt-get update && sudo apt-get install synk-to-html -y
     mkdir -p sync-result
     synk auth $(SYNC_TOKEN)
     synk test --all-projects
     env:
      SYNC_TOKEN = $(SYNC_TOKEN)
    didisplayName: 'Security Scan'
