micronaut:
  application:
    name: learningJava
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      openapi-explorer:
        paths: classpath:META-INF/swagger/views/openapi-explorer
        mapping: /openapi-explorer/**
  validation:
    enabled: true
    provider: jakarta
  server:
    error:
      responses:
        enabled: true
    port: 9191
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "verySecretKey-your-super-secure-secret-key-123456"
        generator:
          access-token:
            expiration: 3600
    intercept-url-map:
      - pattern: /auth/login
        http-method: POST
        access: isAnonymous()
my:
  api:
    version: 1.0.0
    description: "to test bidirectional contract testing"

jackson:
  serialization-inclusion: ALWAYS

logger:
  levels:
    io.micronaut.validation: DEBUG
    io.micronaut.http.server: TRACE

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    schema: mn

#flyway:
#  datasources:
#    default:
#      enabled: true
#      clean-schema: true
#      schemas:
#        - mn
#      default-schema: mn
#      locations:
#        - classpath:db/migration
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create  # or create-drop (for dev only)
        dialect: org.hibernate.dialect.PostgreSQLDialect
